### ISSUE TITLE
Video samples ?

### ISSUE THREAD

**Issue by Drumaddict182** [keijiro/BibcamVfx#2]
Hello, where can i find a video sample for this project ? I want to try but i don't have an iPhone 13 pro. 

Thanks a lot.

**Comment by keijiro** [comment]
Please check the following thread: https://github.com/keijiro/Bibcam/issues/10

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen it for further problems.

**Comment by Drumaddict182** [comment]
Ok. Thanks for the very quick reply. I will wait for the video sample.
