### ISSUE TITLE
'This binding is not Correctly configured'

### ISSUE THREAD

**Issue by vettorazi** [keijiro/BibcamVfx#3]
Hi Keijiro,
I'm trying to use the BibcamVFX package in my sample project of bibcam, but when I add the VFX Property Binder Script in the vfx object, it shows orange like this and says that isn't configured correctly. I think it's exactly like yours, what I could be missing here?
<img width="492" alt="Screen Shot 2022-01-12 at 2 24 39 PM" src="https://user-images.githubusercontent.com/7634575/149232914-2f8c1ce0-88cb-4700-a666-cca97b08759f.png">

**Comment by keijiro** [comment]
Does the VFX graph have these properties correctly?

**Comment by vettorazi** [comment]
Yeah. I double checked and tried one from you (the voxels from the sample project too) and same issue.

**Comment by vettorazi** [comment]
@keijiro I figured it out. Explaining to help others with the same mistake:
I was using the original bibcam project. Since I was using it to export the encoder to my IOS device, the platform was wrong and the original bibcam project didn't have HDRP enabled. when I changed these settings, things started to work.

**Comment by mycroftcanner** [comment]
@vettorazi I got Bibcam to work. How did you get Bibcam-vfx to work I get an error saying "Platform iOS with graphics API Metal is not supported with HDRP."

cheers
